[package]
name = "cloudflare_systems_assignment"
version = "0.1.0"
authors = ["keerthivasankrishnamurthy <kkrish39@asu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"